apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app # Name of your deployment
spec:
  replicas: 2 # Desired number of application instances
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      spec:
      containers:
        - name: simple-eks-app-container
          image: 585853585762.dkr.ecr.eu-north-1.amazonaws.com/eks-demo-repo:2
          ports:
            - containerPort: 3000
