apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-eks-app # Name of your deployment
spec:
  replicas: 2 # Desired number of application instances
  selector:
    matchLabels:
      app: simple-eks-app
  template:
    metadata:
      labels:
        app: simple-eks-app
    spec:
      spec:
      containers:
        - name: simple-eks-app-container
          image: 536322508049.dkr.ecr.eu-north-1.amazonaws.com/my-ecr-image:4
          ports:
            - containerPort: 80
